server:
  port: 8083
  

spring:
  application:
    name: RATING-SERVICE
  config:
    import: optional:configserver:http://localhost:8085
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_rating
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
